import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@components/Provider";
import { ErrorProvider } from "@context/ErrorContext";
import { AppProvider } from "@context/AppProviders";
import { AuthNav } from "@components/Nav";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Code Compiler | Host and Participate in Code Competitions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body>
        <Provider>
        <ChakraProvider>
        <AppProvider>
          <ErrorProvider>
          <main>
            {children}
          </main>
          </ErrorProvider>
        </AppProvider>
        </ChakraProvider>
        </Provider>
      </body>
    </html>
  );
}
