import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@components/Provider";
import { ErrorProvider } from "@context/ErrorContext";
import { AppProvider } from "@context/AppProviders";
import { AuthNav } from "@components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
        <AppProvider>
          <ErrorProvider>
          <main>
            <AuthNav/>
            {children}
          </main>
          </ErrorProvider>
        </AppProvider>
        </Provider>
      </body>
    </html>
  );
}
